name: Main publish new version

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                ref: main
            
            - name: Fetch tag
              run: |
                echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
              working-directory: ./CityDistanceService/
            
            - name: Fetch app version
              run: |
                echo "APP_VERSION=$(grep -oP 'Version\s*=\s*"\K[^"]*' ./src/Constants.cs)" >> $GITHUB_ENV
              working-directory: ./CityDistanceService/
            
            - name: Compare tag and version
              run: |
                if [ "${TAG}" != "${APP_VERSION}" ]; then
                  echo "Tag and version do not match"
                  if [ "${TAG}" == "main" ]; then
                    echo "Branch is main, continuing..."
                  else
                    echo "Exiting due to version mismatch"
                    exit 1
                  fi
                fi
              working-directory: ./CityDistanceService/
            
            - name: Build Docker images
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
              run: |
                dotnet restore
                docker build -t app .

                echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin

                IMAGE_NAME="$DOCKER_USERNAME/city-distance-service"
                docker tag app $IMAGE_NAME:$APP_VERSION
                docker tag app $IMAGE_NAME:latest
                docker push $IMAGE_NAME --all-tags  
              working-directory: ./CityDistanceService/
